config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: 'api/v1', as: 'api' do
      get '/current_user' => 'users#show'

      resources :ideas

      resources :associations

      resources :users

      resources :models
    end
    mount VandalUi::Engine, at: '/vandal'
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'ideas#index'
  resources :ideas
  resources :associations, only: %i[new create destroy edit show] do
    resources :steps, only: %i[show update], controller: 'associations/steps'
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
  }
  resources :models, except: :index
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_users_on_email                 (email) UNIQUE
#  index_admin_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association.rb
# == Schema Information
#
# Table name: associations
#
#  id                                     :bigint           not null, primary key
#  finished                               :boolean          default(FALSE)
#  foreign_key                            :string
#  indirect_associations_as_source_count  :integer          default(0)
#  indirect_associations_as_through_count :integer          default(0)
#  name                                   :string
#  nature                                 :integer
#  created_at                             :datetime         not null
#  updated_at                             :datetime         not null
#  foreign_key_location_model_id          :bigint
#  idea_id                                :bigint           not null
#  join_model_id                          :bigint
#  origin_model_id                        :bigint
#  source_association_id                  :bigint
#  terminus_model_id                      :bigint
#  through_association_id                 :bigint
#
# Indexes
#
#  index_associations_on_foreign_key_location_model_id  (foreign_key_location_model_id)
#  index_associations_on_idea_id                        (idea_id)
#  index_associations_on_join_model_id                  (join_model_id)
#  index_associations_on_origin_model_id                (origin_model_id)
#  index_associations_on_source_association_id          (source_association_id)
#  index_associations_on_terminus_model_id              (terminus_model_id)
#  index_associations_on_through_association_id         (through_association_id)
#
# Foreign Keys
#
#  fk_rails_...  (foreign_key_location_model_id => models.id)
#  fk_rails_...  (idea_id => ideas.id)
#  fk_rails_...  (join_model_id => models.id)
#  fk_rails_...  (origin_model_id => models.id)
#  fk_rails_...  (source_association_id => associations.id)
#  fk_rails_...  (terminus_model_id => models.id)
#  fk_rails_...  (through_association_id => associations.id)
#
class Association < ApplicationRecord
  enum nature: { 'direct' => 0, 'indirect' => 1 }

  cattr_accessor :form_steps do
    %w[origin_model terminus_model nature foreign_key_location foreign_key join_table through source name]
  end

  attr_accessor :form_step

  # Direct associations

  belongs_to :idea, counter_cache: true

  belongs_to :foreign_key_location_model,
             class_name: 'Model',
             counter_cache: :foreign_key_locations_count,
             optional: true

  belongs_to :join_model,
             class_name: 'Model',
             counter_cache: :join_models_count,
             optional: true

  belongs_to :through_association,
             class_name: 'Association',
             counter_cache: :indirect_associations_as_through_count,
             optional: true

  has_many   :indirect_associations_as_through,
             class_name: 'Association',
             foreign_key: 'through_association_id',
             dependent: :destroy

  belongs_to :source_association,
             class_name: 'Association',
             counter_cache: :indirect_associations_as_source_count,
             optional: true

  has_many   :indirect_associations_as_source,
             class_name: 'Association',
             foreign_key: 'source_association_id',
             dependent: :destroy

  belongs_to :indirect_terminus_model,
             class_name: 'Model',
             foreign_key: 'terminus_model_id',
             counter_cache: :indirect_terminating_associations_count,
             optional: true

  belongs_to :indirect_origin_model,
             class_name: 'Model',
             foreign_key: 'origin_model_id',
             counter_cache: :indirect_originating_associations_count,
             optional: true

  belongs_to :direct_terminus_model,
             class_name: 'Model',
             foreign_key: 'terminus_model_id',
             counter_cache: :direct_terminating_associations_count,
             optional: true

  belongs_to :direct_origin_model,
             class_name: 'Model',
             foreign_key: 'origin_model_id',
             counter_cache: :direct_originating_associations_count,
             optional: true

  belongs_to :terminus_model,
             class_name: 'Model',
             counter_cache: :terminating_associations_count,
             optional: true

  belongs_to :origin_model,
             class_name: 'Model',
             counter_cache: :originating_associations_count,
             optional: true

  # Indirect associations

  # Validations

  with_options if: -> { form_step == 'origin_model' } do
    validates :origin_model, presence: true
  end

  with_options if: -> { form_step == 'terminus_model' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
  end

  with_options if: -> { form_step == 'nature' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
  end

  with_options if: -> { form_step == 'foreign_key_location' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
    validates :foreign_key_location_model, presence: true
  end

  with_options if: -> { form_step == 'foreign_key' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
    validates :foreign_key_location_model, presence: true
    validates :foreign_key, presence: true, exclusion: { in: %w[id], message: 'with that name not allowed' }
  end

  with_options if: -> { form_step == 'join_table' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
    validates :join_model, presence: true
  end

  with_options if: -> { form_step == 'through' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
    validates :join_model, presence: true
    validates :through_association, presence: true
  end

  with_options if: -> { form_step == 'source' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
    validates :join_model, presence: true
    validates :through_association, presence: true
    validates :source_association, presence: true
  end

  with_options if: -> { form_step == 'name' } do
    validates :origin_model, presence: true
    validates :terminus_model, presence: true
    validates :nature, presence: true
    validates :name, presence: true, uniqueness: { scope: %i[origin_model_id finished] }
  end

  scope :finished, -> { where(finished: true) }

  before_validation :normalize_foreign_key
  before_validation :normalize_name

  after_validation :set_finished

  def to_s
    name
  end

  def normalize_foreign_key
    self.foreign_key = foreign_key.try(:parameterize, separator: '_')
  end

  def normalize_name
    self.name = name.try(:parameterize, separator: '_')
  end

  def set_finished
    self.finished = true if name.present?
  end

  def options_for_nature_select
    [
      ['direct', "Directly: the ID of the #{origin_model.singular_name} is stored in the #{terminus_model.singular_name} record, in a foreign key column (or vice versa)."],
      ['indirect', "Indirectly: the #{origin_model.singular_name} and the #{terminus_model.singular_name} both have an association to a third, joining, record."]
    ]
  end

  def belongs_to?
    foreign_key_location_model == origin_model
  end

  def one?
    if direct?
      belongs_to?
    elsif indirect?
      source_association.one? && through_association.one?
    end
  end

  def many?
    !one?
  end

  def direct_one?
    direct? && one?
  end

  def direct_many?
    direct? && many?
  end

  def indirect_many_one?
    indirect? && through_association.many? && source_association.one?
  end

  def indirect_many_many?
    indirect? && through_association.many? && source_association.many?
  end

  def indirect_one_one?
    indirect? && through_association.one? && source_association.one?
  end

  def indirect_one_many?
    indirect? && through_association.one? && source_association.many?
  end

  def parent_model
    if foreign_key_location_model == origin_model
      terminus_model
    elsif foreign_key_location_model == terminus_model
      origin_model
    end
  end

  def can_eliminate_class_name?
    name.classify == if belongs_to?
                       parent_model.class_name
                     else
                       foreign_key_location_model.class_name
                     end
  end

  def can_eliminate_foreign_key?
    if belongs_to?
      foreign_key.chomp('_id') == name
    else
      foreign_key.chomp('_id').classify == origin_model.class_name
    end
  end
end

app/models/idea.rb
# == Schema Information
#
# Table name: ideas
#
#  id                 :bigint           not null, primary key
#  associations_count :integer          default(0)
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :bigint           not null
#
# Indexes
#
#  index_ideas_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Idea < ApplicationRecord
  # Direct associations

  has_many   :models,
             dependent: :destroy

  belongs_to :user

  # Indirect associations

  has_many :associations, through: :models, source: :originating_associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/models/model.rb
# == Schema Information
#
# Table name: models
#
#  id                                      :bigint           not null, primary key
#  class_name                              :string
#  direct_originating_associations_count   :integer          default(0)
#  direct_terminating_associations_count   :integer          default(0)
#  foreign_key_locations_count             :integer          default(0)
#  indirect_originating_associations_count :integer          default(0)
#  indirect_terminating_associations_count :integer          default(0)
#  join_models_count                       :integer          default(0)
#  name                                    :string
#  originating_associations_count          :integer          default(0)
#  plural_name                             :string
#  singular_name                           :string
#  terminating_associations_count          :integer          default(0)
#  created_at                              :datetime         not null
#  updated_at                              :datetime         not null
#  idea_id                                 :integer
#
class Model < ApplicationRecord
  # Direct associations

  belongs_to :idea

  has_many   :indirect_terminating_associations,
             -> { indirect },
             class_name: 'Association',
             foreign_key: 'terminus_model_id',
             dependent: :destroy

  has_many   :indirect_originating_associations,
             -> { indirect },
             class_name: 'Association',
             foreign_key: 'origin_model_id',
             dependent: :destroy

  has_many   :direct_terminating_associations,
             -> { direct },
             class_name: 'Association',
             foreign_key: 'terminus_model_id',
             dependent: :destroy

  has_many   :direct_originating_associations,
             -> { direct },
             class_name: 'Association',
             foreign_key: 'origin_model_id',
             dependent: :destroy

  has_many   :terminating_associations,
             class_name: 'Association',
             foreign_key: 'terminus_model_id',
             dependent: :destroy

  has_many   :originating_associations,
             class_name: 'Association',
             foreign_key: 'origin_model_id',
             dependent: :destroy

  # Indirect associations

  has_many   :indirect_origin_models,
             through: :indirect_terminating_associations,
             source: :indirect_origin_model

  has_many   :indirect_terminus_models,
             through: :indirect_originating_associations,
             source: :indirect_terminus_model

  # Validations

  validates :class_name, presence: true, uniqueness: { scope: :idea_id }

  # Scopes

  before_validation :normalize_name

  def normalize_name
    self.plural_name = name.pluralize.parameterize(separator: '_')
    self.singular_name = plural_name.singularize
    self.class_name = singular_name.classify
  end

  def to_s
    class_name
  end
end

app/controllers/api/v1/models_controller.rb
class Api::V1::ModelsController < Api::V1::GraphitiController
  def index
    models = ModelResource.all(params)
    respond_with(models)
  end

  def show
    model = ModelResource.find(params)
    respond_with(model)
  end

  def create
    model = ModelResource.build(params)

    if model.save
      render jsonapi: model, status: :created
    else
      render jsonapi_errors: model
    end
  end

  def update
    model = ModelResource.find(params)

    if model.update_attributes
      render jsonapi: model
    else
      render jsonapi_errors: model
    end
  end

  def destroy
    model = ModelResource.find(params)

    if model.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: model
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[show edit update destroy]

  def index
    @q = Model.ransack(params[:q])
    @models = @q.result(distinct: true).includes(:originating_associations, :terminating_associations, :direct_originating_associations, :direct_terminating_associations, :indirect_originating_associations, :indirect_terminating_associations, :idea, :indirect_terminus_models, :indirect_origin_models, :terminus_models, :terminating_associations).page(params[:page]).per(10)
  end

  def show
    @association = Association.new
  end

  def new
    @model = Model.new
  end

  def edit; end

  def create
    @model = Model.new(model_params)

    if @model.save
      message = 'Model was successfully created.'

      redirect_to @model.idea, notice: message
    else
      render :new
    end
  end

  def update
    if @model.update(model_params)
      redirect_to @model, notice: 'Model was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @model.destroy
    message = 'Model was successfully deleted.'
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: @model.idea, notice: message
    else
      redirect_to models_url, notice: message
    end
  end

  private

  def set_model
    @model = Model.find(params[:id])
  end

  def model_params
    params.require(:model).permit(:name, :idea_id)
  end
end

app/views/models/_form.html.erb
<% was_validated = model.errors.any? %>

<%= form_with(model: model, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = model.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% model.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% idea_id_class = "form-control" %>
    <% idea_id_was_invalid = model.errors.include?(:idea_id) %>

    <% if was_validated %>
      <% if idea_id_was_invalid %>
        <% idea_id_class << " is-invalid" %>
      <% else %>
        <% idea_id_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :idea_id %>
    <%= f.select :idea_id, options_from_collection_for_select(Idea.all, :id, :to_s, @model.idea_id), {}, class: "form-control" %>
    <% if idea_id_was_invalid %>
      <% model.errors.full_messages_for(:idea_id).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/models/_model_direct_originating_associations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Direct Originating Associations

    <%= link_to 'Add association', associations_path(association: { idea_id: @model.idea }), method: :post %>
  </div>

  <ul class="list-group list-group-flush">
    <% @model.direct_originating_associations.each do |association| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to association.to_s, association_path(association) %>

        <%= link_to association, method: :delete, data: { confirm: "Do you really want to delete this association" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="model_direct_originating_associations_new_form">
        <%= render partial: "models/model_direct_originating_associations_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/models/_model_direct_originating_associations_new_form.html.erb
<%= form_with(model: @association, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :source_association_id %>
    <%= f.select :source_association_id, options_from_collection_for_select(Association.all, :id, :to_s, @association.source_association_id), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :through_association_id %>
    <%= f.select :through_association_id, options_from_collection_for_select(Association.all, :id, :to_s, @association.through_association_id), {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :origin_model_id, value: @model.id %>

  <div class="form-group">
    <%= f.label :terminus_model_id, "Which table do you want the method to return an associated record(s) from?" %>
    <%= f.text_field :terminus_model_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :foreign_key, "What is the foreign key column called?" %>
    <%= f.text_field :foreign_key, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nature, "For this relationship, how is a row in the #{@association.origin_model.plural_name} table connected to a row in the #{@association.terminus_model.plural_name} table?" %>
    <%= f.select :nature, options_for_select(Association.natures.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create association", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/models/_model_direct_terminating_associations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Direct Terminating Associations

    <%= link_to 'Add association', associations_path(association: { idea_id: @model.idea }), method: :post %>how
  </div>

  <ul class="list-group list-group-flush">
    <% @model.direct_terminating_associations.each do |association| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to association.to_s, association_path(association) %>

        <%= link_to association, method: :delete, data: { confirm: "Do you really want to delete this association" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="model_direct_terminating_associations_new_form">
        <%= render partial: "models/model_direct_terminating_associations_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/models/_model_indirect_origin_models.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Indirect Origin Models
  </div>

  <ul class="list-group list-group-flush">
    <% @model.indirect_origin_models.each do |model| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/models/<%= model.id %>">
          <%= model.name %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/models/_model_indirect_originating_associations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Indirect Originating Associations

    <%= link_to 'Add association', associations_path(association: { idea_id: @model.idea }), method: :post %>
  </div>

  <ul class="list-group list-group-flush">
    <% @model.indirect_originating_associations.each do |association| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to association.to_s, association_path(association) %>

        <%= link_to association, method: :delete, data: { confirm: "Do you really want to delete this association" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="model_indirect_originating_associations_new_form">
        <%= render partial: "models/model_indirect_originating_associations_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/models/_model_indirect_terminating_associations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Indirect Terminating Associations

    <%= link_to 'Add association', associations_path(association: { idea_id: @model.idea }), method: :post %>
  </div>

  <ul class="list-group list-group-flush">
    <% @model.indirect_terminating_associations.each do |association| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to association.to_s, association_path(association) %>

        <%= link_to association, method: :delete, data: { confirm: "Do you really want to delete this association" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="model_indirect_terminating_associations_new_form">
        <%= render partial: "models/model_indirect_terminating_associations_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/models/_model_indirect_terminating_associations_new_form.html.erb
<%= form_with(model: @association, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :source_association_id %>
    <%= f.select :source_association_id, options_from_collection_for_select(Association.all, :id, :to_s, @association.source_association_id), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :through_association_id %>
    <%= f.select :through_association_id, options_from_collection_for_select(Association.all, :id, :to_s, @association.through_association_id), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :origin_model_id, "Which class would you like to add an association accessor method to?" %>
    <%= f.text_field :origin_model_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :terminus_model_id, value: @model.id %>

  <div class="form-group">
    <%= f.label :foreign_key, "What is the foreign key column called?" %>
    <%= f.text_field :foreign_key, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nature, "For this relationship, how is a row in the #{@association.origin_model.plural_name} table connected to a row in the #{@association.terminus_model.plural_name} table?" %>
    <%= f.select :nature, options_for_select(Association.natures.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create association", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/models/_model_indirect_terminus_models.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Indirect Terminus Models
  </div>

  <ul class="list-group list-group-flush">
    <% @model.indirect_terminus_models.each do |model| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/models/<%= model.id %>">
          <%= model.name %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/models/_model_terminating_associations_new_form.html.erb
<%= form_with(model: @association, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :source_association_id %>
    <%= f.select :source_association_id, options_from_collection_for_select(Association.all, :id, :to_s, @association.source_association_id), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :through_association_id %>
    <%= f.select :through_association_id, options_from_collection_for_select(Association.all, :id, :to_s, @association.through_association_id), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :origin_model_id, "Which class would you like to add an association accessor method to?" %>
    <%= f.text_field :origin_model_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :terminus_model_id, value: @model.id %>

  <div class="form-group">
    <%= f.label :foreign_key, "What is the foreign key column called?" %>
    <%= f.text_field :foreign_key, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nature, "For this relationship, how is a row in the #{@association.origin_model.plural_name} table connected to a row in the #{@association.terminus_model.plural_name} table?" %>
    <%= f.select :nature, options_for_select(Association.natures.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create association", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/models/_model_terminus_models.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Terminus Models
  </div>

  <ul class="list-group list-group-flush">
    <% @model.terminus_models.each do |model| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/models/<%= model.id %>">
          <%= model.name %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/models/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Models

      <%= link_to new_model_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%#= render partial: "models/models_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Models

        <%= link_to new_model_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @models, partial: "list_item", as: :model %>
      </div>
    </div>
  </div>
</div>

app/views/models/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Model
      </h2>

      <div class="card-body">
        <%= render "form", model: @model %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>