config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: 'api/v1', as: 'api' do
      get '/current_user' => 'users#show'

      resources :ideas

      resources :associations

      resources :users

      resources :models
    end
    mount VandalUi::Engine, at: '/vandal'
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'ideas#index'
  resources :ideas
  resources :associations, only: %i[new create destroy edit show] do
    resources :steps, only: %i[show update], controller: 'associations/steps'
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
  }
  resources :models, except: :index
end

app/models/idea.rb
# == Schema Information
#
# Table name: ideas
#
#  id                 :bigint           not null, primary key
#  associations_count :integer          default(0)
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :bigint           not null
#
# Indexes
#
#  index_ideas_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Idea < ApplicationRecord
  # Direct associations

  has_many   :models,
             dependent: :destroy

  belongs_to :user

  # Indirect associations

  has_many :associations, through: :models, source: :originating_associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/ideas_controller.rb
class Api::V1::IdeasController < Api::V1::GraphitiController
  def index
    ideas = IdeaResource.all(params)
    respond_with(ideas)
  end

  def show
    idea = IdeaResource.find(params)
    respond_with(idea)
  end

  def create
    idea = IdeaResource.build(params)

    if idea.save
      render jsonapi: idea, status: :created
    else
      render jsonapi_errors: idea
    end
  end

  def update
    idea = IdeaResource.find(params)

    if idea.update_attributes
      render jsonapi: idea
    else
      render jsonapi_errors: idea
    end
  end

  def destroy
    idea = IdeaResource.find(params)

    if idea.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: idea
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :current_user_must_be_idea_user, only: %i[edit update destroy]

  before_action :set_idea, only: %i[show edit update destroy]

  def index
    # @q = Idea.ransack(params[:q])
    # @ideas = @q.result(distinct: true).includes(:user, :models).page(params[:page]).per(10)
    @ideas = current_user.ideas
  end

  def show
    @model = Model.new
  end

  def new
    @idea = Idea.new
  end

  def edit; end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      message = 'Idea was successfully created.'
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @idea, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    message = 'Idea was successfully deleted.'
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to ideas_url, notice: message
    end
  end

  private

  def current_user_must_be_idea_user
    set_idea
    unless current_user == @idea.user
      redirect_back fallback_location: root_path, alert: 'You are not authorized for that.'
    end
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:name, :user_id)
  end
end

app/views/ideas/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    <%= idea.name %>
  </h2>

  <div class="card-body">
    <div class="row">
      <div class="col">
        <%= link_to_show_or_back idea, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @idea.user %>
          <%= link_to edit_idea_url(idea), class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @idea.user %>
          <%= link_to idea, method: :delete, data: { confirm: "Do you really want to delete this idea?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/_form.html.erb
<% was_validated = idea.errors.any? %>

<%= form_with(model: idea, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = idea.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% idea.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/ideas/_idea_associations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Associations
  </div>

  <ul class="list-group list-group-flush">
    <% @idea.associations.finished.order(created_at: :desc).each do |association| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <span>
          <span class="badge badge-secondary">
            <%= association.origin_model.class_name %>
          </span>

          &nbsp;

          <%= link_to association, association %>
        </span>

        <%= link_to association, method: :delete, data: { confirm: "Do you really want to delete this association" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>
  </ul>
</div>

app/views/ideas/_idea_models.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Models
  </div>

  <ul class="list-group list-group-flush">
    <% @idea.models.each do |model| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%#= link_to model.to_s, model_path(model) %>
        <code><%= model %></code>

        <%= link_to model, method: :delete, data: { confirm: "Do you really want to delete this model" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div id="idea_models_new_form">
        <%= render partial: "ideas/idea_models_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/ideas/_idea_models_new_form.html.erb
<%= form_with(model: @model, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.hidden_field :idea_id, value: @idea.id %>

  <%= f.submit "Create model", class: "btn btn-block btn-outline-success" %>
<% end %>

app/views/ideas/_ideas_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "ideas_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "User Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='usergteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :user_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at greater than or equal to", :data => {:target => '#usergteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#usergteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='userlteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :user_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at less than or equal to", :data => {:target => '#userlteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#userlteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#usergteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#userlteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#usergteqcreated_atPicker').on("dp.change", function (e) {
              $('#userlteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#userlteqcreated_atPicker').on("dp.change", function (e) {
              $('#usergteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :models_name_cont, "Model name contains" %>
    <%= f.text_field :models_name_cont, :class => "form-control", :placeholder => "Model name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/ideas" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#ideas_filters">
  Show filters
</a>

app/views/ideas/_list_item.html.erb
<%= link_to idea, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= idea.to_s %>
    <small class="text-muted">
      <%= time_ago_in_words(idea.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/ideas/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Idea #<%= @idea.id %>
      </h2>

      <div class="card-body">
        <%= render "form", idea: @idea %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/index.html.erb
<div class="row">
  <div class="col-md-12 mb-3">
    <%#= render partial: "ideas/ideas_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Ideas

        <%= link_to new_idea_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @ideas, partial: "list_item", as: :idea %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Idea
      </h2>

      <div class="card-body">
        <%= render "form", idea: @idea %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/show.html.erb
<div class="row mb-3">
  <div class="col-md-3">
    <%= render object: @idea, partial: "card", as: :idea %>

     <%= render partial: "ideas/idea_models" %>
  </div>

  <div class="col-md-8">
    <div class="card mb-3">
      <div class="card-body">
        <dl class="mb-4">
          <dt class="mb-3">Let's build a new association accessor!</dt>
          <dd><%= button_to 'Start wizard', associations_path(association: { idea_id: @idea }), method: :post, class: "btn btn-block btn-success" %></dd>

        </dl>
      </div>
    </div>

    <%= render partial: "ideas/idea_associations" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-8">
    
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-8">
    
  </div>
</div>